import type { LaunchMetro, OpsAsset, OpsRegion } from './types';

export const OPS_ASSETS: OpsAsset[] = [
  {
    id: 'tokyo-port',
    metro: 'tokyo',
    region: 'kanto',
    class: 'port',
    name: 'Port of Tokyo',
    lat: 35.617,
    lng: 139.794,
    tags: ['coastal', 'cargo', 'tokyo-bay'],
    minZoomTier: 'national',
  },
  {
    id: 'tokyo-shinagawa',
    metro: 'tokyo',
    region: 'kanto',
    class: 'rail_hub',
    name: 'Shinagawa Station',
    lat: 35.6284,
    lng: 139.7387,
    tags: ['rail', 'transfer', 'tokyo'],
    minZoomTier: 'regional',
  },
  {
    id: 'tokyo-st-lukes',
    metro: 'tokyo',
    region: 'kanto',
    class: 'hospital',
    name: "St. Luke's International Hospital",
    lat: 35.6677,
    lng: 139.7772,
    tags: ['medical', 'access', 'tokyo'],
    minZoomTier: 'city',
  },
  {
    id: 'osaka-port',
    metro: 'osaka',
    region: 'kansai',
    class: 'port',
    name: 'Port of Osaka',
    lat: 34.6389,
    lng: 135.4111,
    tags: ['coastal', 'cargo', 'osaka-bay'],
    minZoomTier: 'national',
  },
  {
    id: 'osaka-shin-osaka',
    metro: 'osaka',
    region: 'kansai',
    class: 'rail_hub',
    name: 'Shin-Osaka Station',
    lat: 34.7335,
    lng: 135.5001,
    tags: ['rail', 'transfer', 'osaka'],
    minZoomTier: 'regional',
  },
  {
    id: 'osaka-ku',
    metro: 'osaka',
    region: 'kansai',
    class: 'hospital',
    name: 'Osaka University Hospital',
    lat: 34.8215,
    lng: 135.5268,
    tags: ['medical', 'access', 'osaka'],
    minZoomTier: 'city',
  },
  {
    id: 'sapporo-port',
    region: 'hokkaido',
    class: 'port',
    name: 'Port of Sapporo',
    lat: 43.0667,
    lng: 141.35,
    tags: ['coastal', 'cargo', 'hokkaido'],
    minZoomTier: 'national',
  },
  {
    id: 'sapporo-station',
    region: 'hokkaido',
    class: 'rail_hub',
    name: 'Sapporo Station',
    lat: 43.0687,
    lng: 141.3508,
    tags: ['rail', 'transfer', 'hokkaido'],
    minZoomTier: 'regional',
  },
  {
    id: 'hokkaido-univ-hospital',
    region: 'hokkaido',
    class: 'hospital',
    name: 'Hokkaido University Hospital',
    lat: 43.0746,
    lng: 141.3416,
    tags: ['medical', 'access', 'hokkaido'],
    minZoomTier: 'city',
  },
  {
    id: 'sendai-port',
    region: 'tohoku',
    class: 'port',
    name: 'Port of Sendai-Shiogama',
    lat: 38.2619,
    lng: 141.0228,
    tags: ['coastal', 'cargo', 'tohoku'],
    minZoomTier: 'national',
  },
  {
    id: 'sendai-station',
    region: 'tohoku',
    class: 'rail_hub',
    name: 'Sendai Station',
    lat: 38.2606,
    lng: 140.8824,
    tags: ['rail', 'transfer', 'tohoku'],
    minZoomTier: 'regional',
  },
  {
    id: 'tohoku-univ-hospital',
    region: 'tohoku',
    class: 'hospital',
    name: 'Tohoku University Hospital',
    lat: 38.2601,
    lng: 140.8575,
    tags: ['medical', 'access', 'tohoku'],
    minZoomTier: 'city',
  },
  {
    id: 'yokohama-port',
    region: 'kanto',
    class: 'port',
    name: 'Port of Yokohama',
    lat: 35.454,
    lng: 139.638,
    tags: ['coastal', 'cargo', 'kanto'],
    minZoomTier: 'national',
  },
  {
    id: 'tokyo-station',
    region: 'kanto',
    class: 'rail_hub',
    name: 'Tokyo Station',
    lat: 35.6812,
    lng: 139.7671,
    tags: ['rail', 'transfer', 'kanto'],
    minZoomTier: 'regional',
  },
  {
    id: 'tokyo-univ-hospital',
    region: 'kanto',
    class: 'hospital',
    name: 'University of Tokyo Hospital',
    lat: 35.7134,
    lng: 139.761,
    tags: ['medical', 'access', 'kanto'],
    minZoomTier: 'city',
  },
  {
    id: 'nagoya-port',
    region: 'chubu',
    class: 'port',
    name: 'Port of Nagoya',
    lat: 35.0844,
    lng: 136.8856,
    tags: ['coastal', 'cargo', 'chubu'],
    minZoomTier: 'national',
  },
  {
    id: 'nagoya-station',
    region: 'chubu',
    class: 'rail_hub',
    name: 'Nagoya Station',
    lat: 35.1709,
    lng: 136.8815,
    tags: ['rail', 'transfer', 'chubu'],
    minZoomTier: 'regional',
  },
  {
    id: 'nagoya-univ-hospital',
    region: 'chubu',
    class: 'hospital',
    name: 'Nagoya University Hospital',
    lat: 35.1549,
    lng: 136.9645,
    tags: ['medical', 'access', 'chubu'],
    minZoomTier: 'city',
  },
  {
    id: 'kobe-port',
    region: 'kansai',
    class: 'port',
    name: 'Port of Kobe',
    lat: 34.6901,
    lng: 135.1955,
    tags: ['coastal', 'cargo', 'kansai'],
    minZoomTier: 'national',
  },
  {
    id: 'kyoto-station',
    region: 'kansai',
    class: 'rail_hub',
    name: 'Kyoto Station',
    lat: 34.9855,
    lng: 135.7586,
    tags: ['rail', 'transfer', 'kansai'],
    minZoomTier: 'regional',
  },
  {
    id: 'kyoto-univ-hospital',
    region: 'kansai',
    class: 'hospital',
    name: 'Kyoto University Hospital',
    lat: 35.0163,
    lng: 135.772,
    tags: ['medical', 'access', 'kansai'],
    minZoomTier: 'city',
  },
  {
    id: 'hiroshima-port',
    region: 'chugoku',
    class: 'port',
    name: 'Port of Hiroshima',
    lat: 34.372,
    lng: 132.454,
    tags: ['coastal', 'cargo', 'chugoku'],
    minZoomTier: 'national',
  },
  {
    id: 'hiroshima-station',
    region: 'chugoku',
    class: 'rail_hub',
    name: 'Hiroshima Station',
    lat: 34.3977,
    lng: 132.4757,
    tags: ['rail', 'transfer', 'chugoku'],
    minZoomTier: 'regional',
  },
  {
    id: 'hiroshima-univ-hospital',
    region: 'chugoku',
    class: 'hospital',
    name: 'Hiroshima University Hospital',
    lat: 34.3853,
    lng: 132.4688,
    tags: ['medical', 'access', 'chugoku'],
    minZoomTier: 'city',
  },
  {
    id: 'takamatsu-port',
    region: 'shikoku',
    class: 'port',
    name: 'Port of Takamatsu',
    lat: 34.35,
    lng: 134.0467,
    tags: ['coastal', 'cargo', 'shikoku'],
    minZoomTier: 'national',
  },
  {
    id: 'takamatsu-station',
    region: 'shikoku',
    class: 'rail_hub',
    name: 'Takamatsu Station',
    lat: 34.3505,
    lng: 134.0465,
    tags: ['rail', 'transfer', 'shikoku'],
    minZoomTier: 'regional',
  },
  {
    id: 'ehime-univ-hospital',
    region: 'shikoku',
    class: 'hospital',
    name: 'Ehime University Hospital',
    lat: 33.8416,
    lng: 132.7875,
    tags: ['medical', 'access', 'shikoku'],
    minZoomTier: 'city',
  },
  {
    id: 'hakata-port',
    region: 'kyushu',
    class: 'port',
    name: 'Port of Hakata',
    lat: 33.6064,
    lng: 130.4181,
    tags: ['coastal', 'cargo', 'kyushu'],
    minZoomTier: 'national',
  },
  {
    id: 'hakata-station',
    region: 'kyushu',
    class: 'rail_hub',
    name: 'Hakata Station',
    lat: 33.5898,
    lng: 130.4206,
    tags: ['rail', 'transfer', 'kyushu'],
    minZoomTier: 'regional',
  },
  {
    id: 'kyushu-univ-hospital',
    region: 'kyushu',
    class: 'hospital',
    name: 'Kyushu University Hospital',
    lat: 33.6116,
    lng: 130.4288,
    tags: ['medical', 'access', 'kyushu'],
    minZoomTier: 'city',
  },
];

export function getMetroAssets(metro: LaunchMetro): OpsAsset[] {
  return OPS_ASSETS.filter((asset) => asset.metro === metro);
}

export function getRegionAssets(region: OpsRegion): OpsAsset[] {
  return OPS_ASSETS.filter((asset) => asset.region === region);
}
