/**
 * build-vs30-grid.ts — Generate Vs30 grid from J-SHIS API data
 *
 * Fetches Vs30 data from J-SHIS (NIED) and produces a 0.1° resolution
 * grid covering Japan. For development, generates synthetic data based
 * on Wald & Allen (2007) terrain-Vs30 correlations.
 *
 * Output: public/data/vs30-grid.json
 *
 * Usage: npx tsx tools/build-vs30-grid.ts
 */

// This tool is a placeholder for the full J-SHIS API pipeline.
// The actual data is generated by tools/generate-data-files.mjs
// which produces representative Vs30 values for Japan.
//
// To connect to the real J-SHIS API:
// URL: https://www.j-shis.bosai.go.jp/map/api/pshm/Y2024/AVR/VS30/meshdata/{z}/{x}/{y}.json
// 1. Fetch 250m mesh data tiles covering Japan
// 2. Average within each 0.1° cell
// 3. Output as { cols, rows, latMin, lngMin, step, data: number[] }

console.log('build-vs30-grid: Use tools/generate-data-files.mjs for development data');
console.log('For production: implement J-SHIS API fetch + 250m → 0.1° averaging');
