/**
 * build-slope-grid.ts — Generate slope grid from GSI DEM tiles
 *
 * Downloads GSI 10m DEM tiles, computes gradient (slope angle),
 * and averages within each 0.1° cell.
 *
 * Output: public/data/slope-grid.json
 *
 * Usage: npx tsx tools/build-slope-grid.ts
 */

// Placeholder — development data generated by tools/generate-data-files.mjs
//
// Production pipeline:
// 1. Download GSI DEM tiles: https://cyberjapandata.gsi.go.jp/xyz/dem/{z}/{x}/{y}.txt
// 2. Parse elevation values per 256×256 tile
// 3. Compute slope: atan(sqrt(dz/dx² + dz/dy²)) in degrees
// 4. Average slope within each 0.1° cell
// 5. Output as { cols, rows, latMin, lngMin, step, data: number[] }

console.log('build-slope-grid: Use tools/generate-data-files.mjs for development data');
console.log('For production: implement GSI DEM fetch + slope calculation + 0.1° averaging');
