/**
 * build-fault-catalog.ts — Generate active fault catalog from AIST data
 *
 * Downloads fault data from AIST (産総研) Active Fault Database,
 * computes Mw estimates via Wells & Coppersmith (1994).
 *
 * Output: public/data/active-faults.json
 *
 * Usage: npx tsx tools/build-fault-catalog.ts
 */

// Placeholder — development data generated by tools/generate-data-files.mjs
//
// Production pipeline:
// 1. Fetch AIST active fault GeoJSON: https://gbank.gsj.jp/activefault/
// 2. Extract polyline segments, fault name, displacement data
// 3. Compute Mw from length: Mw = 4.38 + 1.49 * log10(lengthKm) (Wells & Coppersmith 1994)
// 4. Include activity interval and 30yr probability from HERP evaluations
// 5. Output as ActiveFault[] JSON

console.log('build-fault-catalog: Use tools/generate-data-files.mjs for development data');
console.log('For production: implement AIST API fetch + W&C Mw estimation');
