/**
 * build-jshis-grid.ts — Generate J-SHIS expected intensity grid
 *
 * Fetches 30-year probabilistic seismic hazard data from J-SHIS API,
 * converts to expected JMA intensity at 0.1° resolution.
 *
 * Output: public/data/jshis-hazard-grid.json
 *
 * Usage: npx tsx tools/build-jshis-grid.ts
 */

// Placeholder — development data generated by tools/generate-data-files.mjs
//
// Production pipeline:
// 1. Fetch J-SHIS hazard map data: https://www.j-shis.bosai.go.jp/map/api/
// 2. Extract 30yr exceedance probability → expected intensity per mesh
// 3. Average within each 0.1° cell
// 4. Output as { cols, rows, latMin, lngMin, step, data: number[] }

console.log('build-jshis-grid: Use tools/generate-data-files.mjs for development data');
console.log('For production: implement J-SHIS hazard API fetch + aggregation');
