/**
 * build-prefectures.ts — Generate prefectures GeoJSON from MLIT data
 *
 * Downloads 国土数値情報 administrative boundary data,
 * simplifies polygons, and merges 2020 census population.
 *
 * Output: public/data/prefectures.json
 *
 * Usage: npx tsx tools/build-prefectures.ts
 */

// Placeholder — development data generated by tools/generate-data-files.mjs
//
// Production pipeline:
// 1. Download 国土数値情報 N03 data: https://nlftp.mlit.go.jp/ksj/gml/datalist/KsjTmplt-N03-v3_1.html
// 2. Simplify polygons with topojson-simplify (target: 200KB)
// 3. Merge 総務省 2020 census population per prefecture
// 4. Compute centroid for each prefecture
// 5. Output as Prefecture[] JSON

console.log('build-prefectures: Use tools/generate-data-files.mjs for development data');
console.log('For production: implement MLIT GeoJSON download + simplification + census merge');
